CASE-0: Open home page
vadimevteev/TestRailTesting pull request #1
Opened 2022-02-02 08:17 UTC by vadimevteev

Zero test case, that opens testRail home page

2022-02-02 08:47 UTC, mashadolya requested changes
PR title must have the same name as brunch 
In your case it will be like  **TR-0: Set up selenium driver**

2022-02-02 08:47 UTC, mashadolya commented on TestProject/TestProject/UnitTest1.cs
> +    private readonly string HOME_PAGE_URL = "https://vadimevteev.testrail.io/";
Create `appsettings.json` and store all configuration data

https://weblog.west-wind.com/posts/2018/Feb/18/Accessing-Configuration-in-NET-Core-Test-Projects

2022-02-02 08:47 UTC, mashadolya commented on TestProject/TestProject/UnitTest1.cs
> +}
Please configure adding new line at the end of the file in your IDE

2022-02-02 08:47 UTC, mashadolya commented on TestProject/TestProject/UnitTest1.cs
> +    }
Lets create `DriverFactory.cs` in order to easily access needed driver (Chrome, Firefiox etc)
And define needed driver in `appsetting.json`

2022-02-02 08:52 UTC, mashadolya commented on TestProject/TestProject/UnitTest1.cs
> +    private readonly string HOME_PAGE_URL = "https://vadimevteev.testrail.io/";
Also as I remember `HOME_PAGE_URL` - is not correct C# code convention

2022-02-02 13:47 UTC, mashadolya requested changes

2022-02-02 13:47 UTC, mashadolya commented on TestRailAutomationTest/Driver/DriverFactory.cs
> +        string currentBrowser = DataReader.GetConfig().Browser;
Why not var?

2022-02-02 13:47 UTC, mashadolya commented on TestRailAutomationTest/Driver/DriverFactory.cs
> +        if (_driver != null) return _driver;
Please always put {}

2022-02-02 13:47 UTC, mashadolya commented on TestRailAutomationTest/Driver/DriverFactory.cs
> +            _ => new EdgeDriver()
Would be better to use chrome as default browser

2022-02-02 13:47 UTC, mashadolya commented on TestRailAutomationTest/Driver/DriverFactory.cs
> +    private static IWebDriver? _driver;
I think we should name it like `driver`
By the way static driver will be working only in one thread 
If we want use test parallelization we should have driver instance for each test

2022-02-02 13:47 UTC, mashadolya commented on TestRailAutomationTest/Driver/DriverFactory.cs
> +            "firefox" => new FirefoxDriver(),
Let's create constants for this strings

2022-02-02 13:47 UTC, mashadolya commented on TestRailAutomationTest/Service/DataReader.cs
> +    private static readonly string SettingsPath = @"resources\appsettings.json";
Should be blank line after

2022-02-02 13:47 UTC, mashadolya commented on TestRailAutomationTest/Service/DataReader.cs
> +    }
please always use `var`

2022-02-02 13:47 UTC, mashadolya commented on TestRailAutomationTest/Service/DataReader.cs
> +        Config config = JsonConvert.DeserializeObject<Config>(json);
Can be exception here 
We should handle it

2022-02-02 13:47 UTC, mashadolya commented on TestRailAutomationTest/Test/HomePageTest.cs
> +    public void Start()
Would be better to name `Init`

2022-02-03 09:51 UTC, julsinkevich approved these changes

2022-02-03 10:12 UTC, merged