TR-3: Create test case test
vadimevteev/TestRailTesting pull request #4
Opened 2022-03-09 10:37 UTC by vadimevteev

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Model/TestCase/BaseTestCase.cs
> +
Здесь пустая линия не требуется

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Model/TestCase/BaseTestCase.cs
> +
Так же можно убрать пустую линию после последнего свойства

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Model/TestCase/TestCaseData.cs
> +            "Test Cases"
Можно создать const вместо листа, так как лист содержит только одно значение

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/BasePage.cs
> +        protected void FillInputAfterClick(By inputLocation, string? data)
Возможно стоит создавть отдельный класс для общих действий с элементами, таких как: FillInput, FillInputAfterClick, GetTextFromElement, GetElementLocation and so on и вынести его в Utils

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/CreateProjectPage.cs
> +
Между полями не ставится пустая линия

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/CreateProjectPage.cs
> +        private static readonly By ShowAnnouncementCheckMarkLocation = By.XPath("//input[@id=\"show_announcement\"]");
Может можно сразу искать по id? Так как id -  уникальный элемент на странице

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/BasePage.cs
> +        protected static By GetElementLocation(string commonLocation, string value)
Лучше записывать через лямбда выражения (=>)

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/Project/CreateTestCasePage.cs
> +            By.XPath("//*[@id=\"content-header\"]//div[contains(text(),'Add Test Case')]");
Eсли ты использовал contains, чтобы избавиться от лишних пробелов, то лучше используй normalize-space

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/Project/ProjectOverviewPage.cs
> +        public static readonly By ChartLineLocation = By.XPath("//div[@id=\"chart-line-fc\"]");
Hе обязательно делать экранирование символов (\") можно сразу писасть "//div[@id='chart-line-fc']"

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/Project/ProjectOverviewPage.cs
> +
Между полями пустая линия не ставится

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/Project/ProjectOverviewPage.cs
> +            catch (WebDriverTimeoutException)
Не думаю, что здесь нужна эта проверка.  В каком случае она сработает?

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/Project/TestCase/BaseTestCaseOverviewPage.cs
> +            testCase.AutomationType = " " + GetRequiredPropertyValue(TestCaseProperties.AutomationType);
Не понимаю, для чего нужен пробел)

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/Project/TestCase/BaseTestCaseOverviewPage.cs
> +        private static int ConvertTimeToMinutes(string time)
Я бы вынесла этот метод статическим и вынесла бы в отдельный класс, например, TestCaseHelper

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Page/Project/TestCase/ExploratoryTestCaseOverviewPage.cs
> +
Пустая линия вроде бы не нужна

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Service/TestCaseCreator.cs
> +            FillRequiredFields(testCase, TestCaseData.TextTemplate);
Строки 18-19, 27-28, 36-37 повторяются. Можно создать отдельный метод с двумя параметрами и назвать типа FillFields()

2022-03-11 12:19 UTC, julsinkevich commented on TestRailAutomationTest/Utils/RandomData.cs
> +        public static string GetWord()
Bogus позволят сразу генерировать объект faker на основе твоей модели, то есть пропадет необходимость генерировать построчно

2022-03-14 19:16 UTC, vadimevteev commented on TestRailAutomationTest/Page/BasePage.cs
> +        protected void FillInputAfterClick(By inputLocation, string? data)
Думал вообще об этом, но в целях уменьшении кода сделал так, поскольку эти методы вызываются в и так довольно громоздкой структуре, если их вызывать еще и через статику то читаемость мне кажется еще понизится

2022-03-14 19:17 UTC, vadimevteev commented on TestRailAutomationTest/Page/CreateProjectPage.cs
> +        private static readonly By ShowAnnouncementCheckMarkLocation = By.XPath("//input[@id=\"show_announcement\"]");
Опять же насколько я осведомлен, лучше оставлять единый селектор для всех элементов на странице

2022-03-14 19:19 UTC, vadimevteev commented on TestRailAutomationTest/Page/Project/CreateTestCasePage.cs
> +            By.XPath("//*[@id=\"content-header\"]//div[contains(text(),'Add Test Case')]");
![photo_2022-03-14_22-18-50](https://user-images.githubusercontent.com/59253494/158245174-453f31f2-17b5-4d35-bb05-9af6901d4a07.jpg)

2022-03-14 19:20 UTC, vadimevteev commented on TestRailAutomationTest/Page/Project/CreateTestCasePage.cs
> +            By.XPath("//*[@id=\"content-header\"]//div[contains(text(),'Add Test Case')]");
тут при таком поиске несколько элементов подходят, поэтому решил что лучше через contains сделать

2022-03-14 19:22 UTC, vadimevteev commented on TestRailAutomationTest/Page/Project/ProjectOverviewPage.cs
> +            catch (WebDriverTimeoutException)
поскольку announcement есть не у всех проектов, и по-другому это никак не увидеть на странице проекта, то есть он либо есть либо нет

2022-03-14 19:23 UTC, vadimevteev commented on TestRailAutomationTest/Page/Project/TestCase/BaseTestCaseOverviewPage.cs
> +            testCase.AutomationType = " " + GetRequiredPropertyValue(TestCaseProperties.AutomationType);
На сайте почему-то он находится в списке с пробелом в начале, то есть чтобы модели верно сравнивались потом

2022-03-14 19:24 UTC, vadimevteev commented on TestRailAutomationTest/Utils/RandomData.cs
> +        public static string GetWord()
тут, если честно, не совсем понял о чем ты)

2022-03-14 19:36 UTC, mashadolya requested changes

2022-03-14 19:36 UTC, mashadolya commented on TestRailAutomationTest/Page/CreateProjectPage.cs
> +        private static readonly By ShowAnnouncementCheckMarkLocation = By.XPath("//input[@id=\"show_announcement\"]");
айдишка всегда уникальна, нам нет смысла искать инпут у которого айди равен чему то там

2022-03-14 19:36 UTC, mashadolya commented on TestRailAutomationTest/Page/Project/CreateTestCasePage.cs
> +            if (testCase is DefaultTestCase) return;
всегда ставим скобочки

2022-03-14 19:36 UTC, mashadolya commented on TestRailAutomationTest/Page/Project/ProjectOverviewPage.cs
> +        public static readonly By ChartLineLocation = By.XPath("//div[@id=\"chart-line-fc\"]");
ну и тут опять таки айдишка

2022-03-14 19:36 UTC, mashadolya commented on TestRailAutomationTest/Page/Project/ProjectOverviewPage.cs
> +        public Model.Project.Project GetProject()
Model.Project.Project GetProject
можно в юзинги вынести

2022-03-14 19:36 UTC, mashadolya commented on TestRailAutomationTest/Page/Project/ProjectOverviewPage.cs
> +            catch (WebDriverTimeoutException)
ну да, возможно, норм 
таймаут главное чтобы не большой был

2022-03-14 19:36 UTC, mashadolya commented on TestRailAutomationTest/Page/Project/TestCase/BaseTestCaseOverviewPage.cs
> +            testCase.AutomationType = " " + GetRequiredPropertyValue(TestCaseProperties.AutomationType);
оставь DEV_NOTE:

2022-03-14 19:36 UTC, mashadolya commented on TestRailAutomationTest/Page/Project/TestCase/DefaultTestCaseOverviewPage.cs
> +        }
как то странно выглядит 
понимаю если бы FillCommonFields возвращал тест кейс

2022-03-14 19:36 UTC, mashadolya commented on TestRailAutomationTest/Page/Project/TestCase/StepsTestCaseOverviewPage.cs
> +            var testCase = new StepsTestCase();
нужно избегать жесткой связанности

2022-03-14 19:36 UTC, mashadolya commented on TestRailAutomationTest/Test/CreateTestCase.cs
> +            CreateTestCaseTest(TestCaseCreator.CreateRandomRequiredFields(), DefaultTestCaseOverViewPage);
что то слишком сложно 
Старайся придерживаться 
Arrange 
Act 
Assert

при таком раскалде как сейчас вообще непонятно что делает этот тест и тест это вообще или нет

2022-03-18 13:42 UTC, mashadolya requested changes

2022-03-18 13:42 UTC, mashadolya commented on TestRailAutomationTest/Model/ProjectModel/ProjectData.cs
> +            return RandomData.Faker.PickRandom<ProjectType>();
лучше сверху через юзинг сделать

2022-03-18 13:42 UTC, mashadolya commented on TestRailAutomationTest/Page/BasePage.cs
> +        protected void FillInputAfterClick(By inputLocation, string? data)
ну это не критично

2022-03-18 13:42 UTC, mashadolya commented on TestRailAutomationTest/Page/CreateProjectPage.cs
> +                    throw new IncorrectDataException("Incorrect project type");
стоит добавить еще какой проджект тайп был передан

2022-03-18 13:42 UTC, mashadolya commented on TestRailAutomationTest/Test/CreateTestCase.cs
> +        private void CreateTestCaseTest(BaseTestCase expectedTest, BaseTestCaseOverviewPage currentPage)
давай все таки добавим степы вместо этого огромного метода

LoginSteps.Login();
ProjectSteps.CreateProject(); 

и тд

2022-03-18 13:42 UTC, mashadolya commented on TestRailAutomationTest/Utils/TestCaseHelper.cs
> +                result = timeMeasurements.FirstOrDefault() * 60;
в константу вынеси число

2022-03-22 22:28 UTC, mashadolya requested changes

2022-03-22 22:28 UTC, mashadolya commented on TestRailAutomationTest/Steps/LoginSteps.cs
> +        public static void Login(LoginPage loginPage, IEnumerable<User?> users)
вряд ли мы сможем логиниться под несколькими юзерами
Поэтому метод должен принимать объект , а не список

2022-03-22 22:28 UTC, mashadolya commented on TestRailAutomationTest/Steps/ProjectSteps.cs
> +        public static void CreateProject(HomePage homePage, CreateProjectPage createProjectPage, ProjectsMenuPage projectsMenuPage, Project project)
лучше инжектить необходимые классы через конструктор 
тогда не нужно будет пробрасывать их в каждый метод

2022-03-22 22:28 UTC, mashadolya commented on TestRailAutomationTest/Test/CreateTestCase.cs
> +                .BeEquivalentTo(actualTest, options => options.Excluding(o => o.Template));
старайся следовать ААА
```
Arrange
Act
Assert
```

2022-03-22 22:28 UTC, mashadolya commented on TestRailAutomationTest/Test/CreateTestCase.cs
> +            LoginSteps.Login(LoginPage, Users);
можно логин и тд вынести в какой нибудь аттрибут типа SetUp

2022-03-22 22:28 UTC, mashadolya commented on TestRailAutomationTest/Page/CreateProjectPage.cs
> +                    throw new IncorrectDataException($"Project type {projectType.ToString()} doesn't exist");
мне кажется toString тут избыточный

2022-03-25 08:14 UTC, mashadolya requested changes

2022-03-25 08:14 UTC, mashadolya commented on TestRailAutomationTest/Steps/LoginSteps.cs
> +        public LoginSteps(LoginPage loginPage, User user)
Ну юзера все таки лучше в метод логина передавать
тогда имея один объект логинСтепсов мы сможем логиниться под разными юзерами (сохраняем гибкость )

2022-03-25 08:14 UTC, mashadolya commented on TestRailAutomationTest/Steps/ProjectSteps.cs
> +        public ProjectSteps(HomePage homePage, CreateProjectPage createProjectPage, ProjectsMenuPage projectsMenuPage, Project project)
Аналогично с юзером проджект кидаем в метод, а странички оставляем в конструкторе

2022-03-27 10:03 UTC, merged