TR-5: Add logging
vadimevteev/TestRailTesting pull request #6
Opened 2022-04-01 03:15 UTC by vadimevteev

2022-04-06 15:46 UTC, Maria-Dolia requested changes

2022-04-06 15:46 UTC, Maria-Dolia commented on TestRailAutomationTest/Logger/Logging.cs
> +    }
Я бы это в сами компоненты врапперы вынесла
то есть, у тебя есть какой то общий класс элемент и в нем методы клик, сет велюе и тд и в этих методах дергать логгер и передавать имя элемента - действие 

тогда будет работать для любого элемента

2022-04-07 06:57 UTC, AlexanderHoha commented on TestRailAutomationTest/Page/CreateProjectPage.cs
>                  ClickButton(ShowAnnouncementCheckMarkLocation);
Нужно сделать отдельный враппер для кнопки и в метод Клик вшить логирование

2022-04-07 06:57 UTC, AlexanderHoha commented on TestRailAutomationTest/Page/CreateProjectPage.cs
> +            new Input(Driver,NameInputId,"Name" ).SetValue(project.Name);
вместо того чтобы при каждом взаимодействии с элементом на страничке писать new Blabla() лучше вынести элемент страницы в отдельное поле, т.е. что типо такого:
private Input NameInput => new Input();
Это будет гораздо более читабельно и посторонний человек сразу может видеть какие элементы есть на страничке.

2022-04-07 06:57 UTC, AlexanderHoha commented on TestRailAutomationTest/Page/CreateProjectPage.cs
>          public CreateProjectPage FillAddProjectForm(Model.ProjectModel.Project project)
Все взаимодействие со страницей лучше делать через отдельный класс степов, т.е. в самом тесте со страничкой мы не работаем, все идет через степы. Использование степов повышает читабельность и удобство работы со страничкой. Даже если новый человек придет на проект и зайдет в степы там сразу будут видны законченный варианты взаимодействия со страницей.

2022-04-07 06:57 UTC, AlexanderHoha commented on TestRailAutomationTest/Page/CreateProjectPage.cs
>                      ClickButton(SingleSuiteModeLocation);
Отдельный метод ClickButton хорош до тех пор, пока логика одинаковая для всех кнопок на странице.
Лучше сделать отдельный враппер Баттон и там обрабатывать клики. При необходимости наследуешься от базового враппера Баттон и там обрабатываешь разные варианты кликов

2022-04-07 06:57 UTC, AlexanderHoha commented on TestRailAutomationTest/Page/Project/CreateTestCasePage.cs
> +            new Input(Driver, TestCaseProperties.Title,"Title").Click().SetValue(testCase.Title);
Вот тут нужно сделать отдельный враппер для этой формы и через этот враппер уже ее заполнять потому как это сложный элемент и в целях повышения поддерживаемости и удобства целесообразно будет в отдельный компонент вынести

2022-04-07 06:57 UTC, AlexanderHoha commented on TestRailAutomationTest/Page/Project/CreateTestCasePage.cs
> -                    new Input(Driver, ReplaceValue(CommonDescriptionId, TestCaseProperties.Mission))
А вот тут можно сделать врапперы для каждого варианта заполнения этой формы и через степы ее заполнять

2022-04-07 06:57 UTC, AlexanderHoha commented on TestRailAutomationTest/Wrapper/BaseWrapper.cs
>          protected const string Example = "EXAMPLE";
Что за поле example?

2022-04-07 06:57 UTC, AlexanderHoha commented on TestRailAutomationTest/Wrapper/BaseWrapper.cs
>          protected readonly By ElementId;
Судя по названию поля элементы у тебя только по айдишнику ищутся

2022-04-07 06:57 UTC, AlexanderHoha commented on TestRailAutomationTest/Wrapper/DropDown.cs
>              var valueXpath = $"//div[@id=\"{ElementId.Criteria[1..]}\"]//li[contains(text(),\"{value}\")]";
Поиск опции дропдауна вынести в отдельный метод
Если опций в дропдауне немного - есть смысл сделать отдельную коллекцию в этом классе для их хранения, условно что то типо такого: private List<DropDownOption> Options

2022-04-10 17:05 UTC, AlexanderHoha commented on TestRailAutomationTest/Page/HomePage.cs
> +        private ButtonLink ProjectLink(string projectName) => new(Driver, $"//a[text()=\"{projectName}\"]", projectName);
Икспас можно вынести как private By ProjectLinkBy(string projectName) => By.XPath($"//a[text()=\"{projectName}\"]")

2022-04-10 17:05 UTC, AlexanderHoha commented on TestRailAutomationTest/Test/CreateProjectTest.cs
> +            LoginSteps loginSteps = new(LoginPage);
Инициализацию степов можно вынести в сетап

2022-04-10 17:05 UTC, AlexanderHoha commented on TestRailAutomationTest/Test/CreateProjectTest.cs
>              ValidateAnnouncement(expectedProject, actualProject);
private static void ValidateAnnouncement(Project expectedProject, Project actualProject) 
нужно вынести из класса тестов - в тесте только там сам тест, никаких утилок быть не должно

2022-04-10 17:05 UTC, AlexanderHoha commented on TestRailAutomationTest/WebElement/Wrapper/Button.cs
> +        Waits.WaitElementExistence(Driver, ElementPath).Click();
Чтобы каждый раз не писать Waits.WaitElementExistence() можно вынести IWebElement как поле враппера, будет как то так:
private IWebElement _element => Waits.WaitElementExistence()

2022-04-11 11:51 UTC, mashadolya requested changes

2022-04-11 11:51 UTC, mashadolya commented on TestRailAutomationTest/Page/BasePage.cs
> +        protected const string Label = "LABEL";
Чего не хочешь как метод сделать, который лейбл будет принимать?

2022-04-11 11:51 UTC, mashadolya commented on TestRailAutomationTest/Utils/LoggerHelper.cs
> +    public static class LoggerHelper
`WebElement/Utils/ActionsLogger.cs`

2022-04-11 11:51 UTC, mashadolya commented on TestRailAutomationTest/Utils/ProjectHelper.cs
> +public static class ProjectHelper
`../Project/Assertions/ProjectAsserions.cs`

2022-04-11 11:51 UTC, mashadolya commented on TestRailAutomationTest/WebElement/Service/WrapperHelper.cs
> +public static class WrapperHelper
`SearchStrategy.cs`

2022-04-11 11:51 UTC, mashadolya commented on TestRailAutomationTest/WebElement/Service/WrapperHelper.cs
> +public static class WrapperHelper
и будет что то типа 

`SearchStrategy.Id('someId')`

2022-04-11 11:51 UTC, mashadolya commented on TestRailAutomationTest/WebElement/Wrapper/BaseWrapper.cs
> +    public abstract class BaseWrapper
`BaseElementWrapper` так будет понятнее

потому что враппер может быть и не только на вэбэлемент, а на форму, к примеру

2022-04-11 12:26 UTC, merged